name = "OTP"

[action]
type = "HttpApi"

[action.headers.auth]
X-Api-Token = [ "xxx" ]

[[action.targets]]
headers_name = "auth"
url = "https://otp-push.fortime.fyi:8443/api/client/otp/fcitx5-osk/request"
method = "POST"
need_enter = true
